apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: devops-learning
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/t1mssc/devops-learning"
    targetRevision: main
    path: devops-pipeline-time-printer
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: default  
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true