image:
  repository: timss/devops-learning
  tag: 9b04c21
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports: 9002
ingress: 
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: 
  parentRefs: []     