image:
  repository: timss/devops-learning
  tag: 81b3530
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9002
container:
  port: 8080  
ingress: 
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: 
  parentRefs: []     