---
name: DevOps Pipeline Learning

on:
  push:
    branch:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set shorts SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build docker image
        run: |
          docker build -t timss/devops-learning:${{ env.SHORT_SHA }} .
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push to Docker Hub
        run: |
          docker push timss/devops-learning:${{ env.SHORT_SHA }}
      - name: Configure Git Author
        run: |
          git config --local user.name "CJ Castillo" 
      - name: Update Helm Chart with new Image Tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./devops-pipeline-time-printer/values.yaml
          git add  ./devops-pipeline-time-printer/values.yaml
          git commit -m "Updated image tag to ${{ env.SHORT_SHA }}"
          git push     
